### ISSUE TITLE
Cannot push from remote terminal

### ISSUE THREAD

**Issue by JiliJiang** [JiliJiang/urban-octo-telegram#1]
Failed to push from remote local terminal.
Returned error 403, indicating access to coding-boot-camp/urban-octo-telegram.git denied.
Screenshot attached here. ![Screenshot 2021-08-07 003718](https://user-images.githubusercontent.com/73008338/128594858-57db792f-f1b8-47b6-80fd-ca2fb1ff70de.jpg)
@Xandromus

**Comment by Xandromus** [comment]
@JiliJiang You shouldn't be pushing to this repo. After you've cloned it down, you need to create your own repo and copy the starter code into it

**Comment by Xandromus** [comment]
@JiliJiang You are trying to push to the starter code repo, which you don't have access to. You need to be in the directory for this repo on your computer

**Comment by JiliJiang** [comment]
I see.  I will re-create the repo.

**Comment by JiliJiang** [comment]
New repo will be set up.  This repo will be archived.

**Comment by JiliJiang** [comment]
New repo created.  Issue closed.  This repo will be archived.
